language: node_js
node_js:
  - '4.1'
cache:
  directories:
  - node_modules
before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_KEY
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info
install: 
  - npm install eslint@^1.0.0 eslint-loader@^1.0.0 eslint-plugin-react@^3.5.1 babel-eslint@^4.0.5
script:
#  - npm run serve & npm test
  - npm run lint
  - npm run lint:checkstyle
#  - npm run swagger:validate
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
