swagger: "2.0"
info:
  version: "0.0.1"
  title: DBC Service Provider
  description: |
    Public API for DBC Services
    
    __NB: Under development, this document does not reflect the actual state of the API__
basePath: /api/
schemes:
  - https
  - wss
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    get:
      tags:
        - user 
      description: Get information about the currently logged in user
      parameters:
        - name: fields
          in: query
          description: Field selector, chooses which parts of the user-info object to return.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SearchResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /search:
    get:
      tags:
        - search
      description: Searches for a string using OpenSearch
      parameters:
        - name: query
          in: query
          description: Query string
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SearchResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  SearchResponse:
    required:
      - results
    properties:
      results:
        type: any
  ErrorResponse:
    required:
      - statusCode
      - errors
    properties:
      statusCode:
        type: integer
      errors:
        type: any
externalDocs:
  description: Extra documentation in the github repository
  url: https://github.com/DBCDK/serviceprovider/tree/master/doc
